# Generated by Django 3.0.3 on 2020-03-12 12:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('cart_date', models.DateField(default=datetime.datetime.now)),
                ('prd_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoeapp.Product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoeapp.User')),
            ],
        ),
    ]
